# Homework

#### Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from [06-environment.md](https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/01-intro/06-environment.md)

In [3]:
import numpy as np
import pandas as pd

#### Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the \_version\_ field:

In [5]:
pd.__version__

'2.2.2'

### Getting the data
For this homework, we'll use the Laptops Price dataset. Download it from [here.](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv)

https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

In [7]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'

In [8]:
df = pd.read_csv('laptops.csv')

In [9]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

#### Q2. Records count
How many records are in the dataset?

In [11]:
record_count = df.shape[0]
print(f"There are {record_count} records in the dataset.")

There are 2160 records in the dataset.


#### Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [13]:
df.Brand.nunique()

27

#### Q4. Missing values
How many columns in the dataset have missing values?

In [15]:
df.isna().sum().sort_values(ascending=False)

GPU             1371
Storage type      42
Screen             4
Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Touch              0
Final Price        0
dtype: int64

#### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [17]:
df.Brand.unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [18]:
# Filter for Dell notebooks
dell_laptops = df[df['Brand'] == 'Dell']

# Find the maximum final price for Dell notebooks
max_final_price = dell_laptops['Final Price'].max()

# Display the result
print(f"The maximum final price of Dell notebooks is: {max_final_price}")


The maximum final price of Dell notebooks is: 3936.0


#### Q6. Median value of Screen
- Find the median value of Screen column in the dataset.
- Next, calculate the most frequent value of the same Screen column.
- Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
- Now, calculate the median value of Screen once again.

Has it changed?

In [20]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [21]:
# Find the median value of Screen column in the dataset.
median_screen = df.Screen.median()
median_screen

15.6

In [22]:
# Next, calculate the most frequent value of the same Screen column.
most_frequent_screen = df.Screen.mode()[0]
most_frequent_screen

15.6

In [23]:
# Fill missing values in "Screen" column with the most frequent value
df.fillna({'Screen': most_frequent_screen}, inplace=True)

In [24]:
# Now, calculate the median value of Screen once again.
median_screen_after = df.Screen.median()
median_screen_after

15.6

In [25]:
if median_screen == median_screen_after:
    print("No, it hasn't changed")
else:
    print("Yes, it has changed")

No, it hasn't changed


#### Q7. Sum of weights
- Select all the "Innjoo" laptops from the dataset.
- Select only columns RAM, Storage, and Screen.
- Get the underlying NumPy array. Let's call it $X$.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Compute the inverse of XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [27]:
# Select all the "Innjoo" laptops from the dataset.
innjoo_laptop = df[df.Brand == 'Innjoo']
innjoo_laptop

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [28]:
# Select only columns RAM, Storage, and Screen.
df_X = innjoo_laptop[['RAM', 'Storage', 'Screen']]
df_X

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [29]:
# Get the underlying NumPy array. Let's call it X
X = df_X.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [30]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [31]:
# Compute the inverse of XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [32]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [33]:
# Multiply the inverse of XTX with the transpose of X, then multiply the result by y. Call the result w.
w = XTX_inv.dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [34]:
# What's the sum of all the elements of the result?
w_sum = w.sum()
w_sum

91.29988062995815